name: Build BlazeCRT
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build Plugin (Release x64)
      env:
        AE_PLUGIN_BUILD_DIR: ..\..\Builds
      run: msbuild BlazeCRT/Win/BlazeCRT.vcxproj /p:Configuration=Release /p:Platform=x64 /p:AdditionalOptions="/openmp /arch:AVX2 /fp:fast"

    - name: Commit Compiled Plugin to Repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add Builds/
        git commit -m "Auto-compiled BlazeCRT.aex (v3.0 Complete Edition)"
        if ($LASTEXITCODE -eq 0) { git push } else { echo "No changes to commit" }
      shell: powershell
